Name:         brewz
Namespace:    default
Labels:       app.kubernetes.io/instance=brewz
Annotations:  <none>
API Version:  k8s.nginx.org/v1
Kind:         VirtualServer
Metadata:
  Creation Timestamp:  2022-07-06T16:51:10Z
  Generation:          1
  Managed Fields:
    API Version:  k8s.nginx.org/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app.kubernetes.io/instance:
      f:spec:
        .:
        f:host:
        f:http-snippets:
        f:routes:
        f:server-snippets:
        f:upstreams:
    Manager:      argocd-application-controller
    Operation:    Update
    Time:         2022-07-06T16:51:10Z
    API Version:  k8s.nginx.org/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:externalEndpoints:
        f:message:
        f:reason:
        f:state:
    Manager:         Go-http-client
    Operation:       Update
    Subresource:     status
    Time:            2022-07-06T16:51:11Z
  Resource Version:  6304
  UID:               c137a6c1-7072-4afb-a12d-16b727936b13
Spec:
  Host:             brewz.f5demo.com
  Routes:
    Action:
      Pass:  spa
    Matches:
      Action:
        Pass:  spa-dark
      Conditions:
        Cookie:  app_version
        Value:   dark
    Path:        /
    Action:
      Pass:  api
    Path:    /api
    Policies:
      Name:  rate-limit-policy
    Action:
      Proxy:
        Rewrite Path:  /api/inventory
        Upstream:      inventory
    Path:              /api/inventory
    Action:
      Proxy:
        Rewrite Path:  /api/recommendations
        Upstream:      recommendations
    Path:              /api/recommendations
    Action:
      Proxy:
        Rewrite Path:  /images
        Upstream:      api
    Path:              /images
    Upstreams:
    Name:     spa
    Port:     80
    Service:  spa
    Name:     spa-dark
    Port:     80
    Service:  spa-dark
    Name:     api
    Port:     8000
    Service:  api
    Name:     inventory
    Port:     8002
    Service:  inventory
    Name:     recommendations
    Port:     8001
    Service:  recommendations
Status:
  External Endpoints:
    Ip:     10.1.1.5
    Ports:  [80,443]
  Message:  Configuration for default/brewz was added or updated
  Reason:   AddedOrUpdated
  State:    Valid
Events:     <none>